### ISSUE TITLE
.default method

### ISSUE THREAD

**Issue by esperanc** [johnwalley/d3-simple-slider#125]
It seems the .value method cannot be used to set a default value. The proper method is .default. It took me a while to figure this out, as it is not in the documentation.

**Comment by johnwalley** [comment]
Thanks for spotting this. I agree that it is confusing. I've released a new version which I hope makes the slider behave as you'd expect: https://github.com/johnwalley/d3-simple-slider/releases/tag/v1.7.0.

I'll review the documentation as well when I get the chance.
