### ISSUE TITLE
Change `min` and `max` values dynamically

### ISSUE THREAD

**Issue by thomasahle** [johnwalley/d3-simple-slider#126]
I have a slider for which the `max` value depends on another slider.

(Imagine for example that the product of the values of the two sliders must be below a certain value, so as the first one goes to 0, the max of the other grows very large.)

I have tried to just call `.max(new_max)` directly on the slider object.
I have also tried to then do a new `.call()` like this:

      this.my_slider = this.my_slider.max(new_max);
      d3.select('#g_slider').call(this.my_slider);

But it also has no effect.

Is there a recommended way to change the maximum of a slider like this? Preferrably without dispatching any "onchange" events.

**Comment by johnwalley** [comment]
Hi @thomasahle. That's a good question and I think you've found a limitation in how .max() works. I'll look into it at some point over the next week.

I know it's not what solving exactly your problem but https://codepen.io/johnwalley/pen/RvPYvw is an example of multiple sliders with constraints if it is of any help.

**Comment by johnwalley** [comment]
I've got something working in https://github.com/johnwalley/d3-simple-slider/pull/131. It needs some testing then I'll publish a new version

**Comment by thomasahle** [comment]
Awesome! I'll test it out myself too!

**Comment by johnwalley** [comment]
This has been published as [v1.8.0](https://github.com/johnwalley/d3-simple-slider/releases/tag/v.1.8.0)
