### ISSUE TITLE
slider.silentValue and slider.value are now identical; .value does not notify listeners

### ISSUE THREAD

**Issue by jrgm** [johnwalley/d3-simple-slider#134]
I assume this was a copy-paste error in https://github.com/johnwalley/d3-simple-slider/commit/cf2cae5904ab5bbd778d9868ea4b1c7c7ad29777. At any rate keypress events no longer dispatch onchange events.

**Comment by johnwalley** [comment]
Hi @jrgm. Apologies for the delay in replying. I'll take a look at this today.

**Comment by johnwalley** [comment]
You're absolutely right it was a copy-paste error. I've published a new version ([1.7.1](https://www.npmjs.com/package/d3-simple-slider/v/1.7.1)) which hopefully addresses the issue. Thanks again for reporting this.

**Comment by jrgm** [comment]
Thanks. 1.7.1 works for me.
