### ISSUE TITLE
compatibility issue?

### ISSUE THREAD

**Issue by qmffkem** [johnwalley/d3-simple-slider#151]
i think the current version of the slider does not work with the current version of d3 v6, as it displays "TypeError: Cannot read property 'ctrlKey' of null" when trying to slide the bar. Could it be because they changed all the event handlers on newer version? 
The code I used were directly from the readme:
  var slider = d3
    .sliderHorizontal()
    .min(0)
    .max(10)
    .step(1)
    .width(300)
    .displayValue(false)
    .on('onchange', (val) => {
      d3.select('#value').text(val);
    });

  d3.select('#slider')
    .append('svg')
    .attr('width', 500)
    .attr('height', 100)
    .append('g')
    .attr('transform', 'translate(30,30)')
    .call(slider);

**Comment by johnwalley** [comment]
Thanks for reporting this. I suspect it's related to the non-backwards compatible changes to the event system in v6. I need to take a look at what's changed and do some testing. It would also be nice to support both v5 and v6 for a while as I suspect there is a lot of code out there which needs upgrading manually (like this library!).

**Comment by johnwalley** [comment]
I've started work on updating the library to work with d3 v6 here: #152. The changes are straightforward enough but I'm holding off on releasing v2 (this would be a breaking change) of this library until I've decided how to maintain support for d3 v5. In the meantime I've published `v2.0.0-rc.1` for anyone who wants to use d3-simple-slider with d3 v6.

**Comment by qmffkem** [comment]
Thank you for the update!

**Comment by johnwalley** [comment]
I've come up with a better way of supporting d3 v6 in #158. We can detect which version of d3 is present and adapt accordingly. I anticipate releasing this as `v1.10.0` once testing is complete.

**Comment by johnwalley** [comment]
Released! https://github.com/johnwalley/d3-simple-slider/releases/tag/v1.10.0
