### ISSUE TITLE
Change label padding

### ISSUE THREAD

**Issue by Programmer1228** [johnwalley/d3-simple-slider#155]
Hi - 

First - REALLY enjoy using d3-simple-slider.

I've been trying to figure out how to change the label padding (distance) from the slider line. D3 has a similar builtin feature with ".tickPadding(#)". I am able to change the padding when the page loads, but once a user clicks on the slider, it reverts to default settings. Is this possible to change on load?

**Comment by johnwalley** [comment]
Hi @Programmer1228. That's a good question and something we should support.

I've created PR #156 to add a new `tickPadding` method which replicates the same method in `d3-axis`. You can see the example story here: https://deploy-preview-156--d3-simple-slider.netlify.app/?path=/story/basic-functionality--padding. I need to do some testing but it doesn't look like there should be any issues so should be merged shortly.

**Comment by johnwalley** [comment]
This has now been published as [`v1.9.0`](https://github.com/johnwalley/d3-simple-slider/releases/tag/v1.9.0).

**Comment by Programmer1228** [comment]
Awesome! Thank you SO much for the quick response! Works as expected!
