### ISSUE TITLE
New York Times example has a bug

### ISSUE THREAD

**Issue by johnmwalley** [johnwalley/d3-simple-slider#159]
The drag zone for the slider does not cover the whole svg so there is a region above which the user might expect to be able to drag but cannot.

<img width="560" alt="Screenshot 2020-09-16 at 10 30 04" src="https://user-images.githubusercontent.com/63664756/93319674-0f662280-f808-11ea-838b-13e4eb9cc690.png">

**Comment by johnwalley** [comment]
Reported this with the wrong account 😄 . It's not so much a bug but a flaw with the example. I've added a workaround in the example for the time being.

**Comment by johnwalley** [comment]
We can revisit whether to make the draggable region customisable at a later date.
