### ISSUE TITLE
default value formatter

### ISSUE THREAD

**Issue by Udneowi** [johnwalley/d3-simple-slider#174]
Hi!

Thanks for this amazing and quick tool !

I'm running into an issue with the formatter used for the default value. 
Right now I have defined both .tickFormat and .displayFormat but the default value will use the tickFormat? After dragging the slider it switches to the displayFormat but not on initialisation. Have I misunderstood something or is this intended use?

let sliderStep = d3.sliderBottom()
    .min(0)
    .max(N-1)
    .width(this.width - this.rwidth - 60)
    .tickValues(indexes)
    .displayFormat(i => this.idxToDate(i))
    .tickFormat(i => this.idxToDate_tick(i))
    .step(1)
    .default(this.t)
    .on('onchange', t => {
        this.t = t;
        this.refreshDrawing();
    });

Before:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/25606256/108347557-f01d5800-71e0-11eb-961a-7758c65bd9de.png">
After:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/25606256/108347579-f7dcfc80-71e0-11eb-8ab0-419246d8199a.png">

**Comment by johnwalley** [comment]
Sounds like a bug! I'll investigate at the weekend and put together a fix.

**Comment by Udneowi** [comment]
Sounds great! 
Thanks for the quick feedback :)

**Comment by johnwalley** [comment]
Just released the fix as v1.10.4 https://github.com/johnwalley/d3-simple-slider/releases/tag/v1.10.4. If you could let me know if it works when you get time to try it out I'd be grateful.

Thanks for reporting this 👍

**Comment by Udneowi** [comment]
It works!
Thanks a lot for the quick fix :)
