### ISSUE TITLE
D3 version 5?

### ISSUE THREAD

**Issue by pmcvay** [johnwalley/d3-simple-slider#23]
How difficult is the library to update for version 5? We can help volunteer time for it as well

**Comment by pmcvay** [comment]
It seems for what we need to do, just deleting the require's allows it to work with v5

**Comment by johnwalley** [comment]
Could you describe the issue you were seeing with version 5? There shouldn't be any incompatible changes which would affect the slider component but I haven't tested it extensively.

**Comment by pmcvay** [comment]
Right - the only issue are the require statements. If the require statements are there, nothing loads. If you delete all of the require statements, it works fine

**Comment by johnwalley** [comment]
The only require statements I can see are in the UMD output for browsers, e.g. `dist/d3-simple-slider.js`. I'd need a reproducible example to diagnose further I'm afraid.
