### ISSUE TITLE
How to import or require after npm install?

### ISSUE THREAD

**Issue by niccololampa** [johnwalley/d3-simple-slider#31]
I am using React how do I import this after using npm install?

import * as d3 from 'd3';
import { sliderBottom } from 'd3-simple-slider';

Then any attempted use such as :

console.log(d3.sliderBottom);

results to the following error: 

Attempted import error: 'sliderBottom' is not exported from 'd3' (imported as 'd3').

**Comment by johnwalley** [comment]
You can use `sliderBottom` by itself, without the `d3` part. So

```
import * as d3 from 'd3';
import { sliderBottom } from 'd3-simple-slider';

console.log(sliderBottom());
```

This is different to including this library as a script in a web page, where it is added to the global d3 object.

I will make this difference clearer in the documentation. Thanks for bringing it to my attention!

**Comment by johnwalley** [comment]
Tracking this in the docs improvement issue #35
