### ISSUE TITLE
Range slider issue/improvement

### ISSUE THREAD

**Issue by lpproulx** [johnwalley/d3-simple-slider#32]
I don't know if it's a bug or just the normal behavior but it's possible to have the lower range slider after the upper range slider. When that happen and you try to select the slider again it disappear and come back only when you stop dragging the slider.

Also, since it's a range selection it would be nice if it was possible to configure it so the minimum range is never smaller than the 'step' so you always have a range and not a single value.

thanks for this great plugin

**Comment by johnwalley** [comment]
Sounds like a bug. I'll try to reproduce and put together a fix. Thanks for reporting.

**Comment by johnwalley** [comment]
I've tried to ensure the lower range slider can never be greater than the upper one in 9dd7d6b8 (release 1.4.2).

I have also created issue #33 to capture the feature request to stop the range becoming a single value if step is defined.

**Comment by sorawee** [comment]
This is actually still not fixed. I will submit a PR to fix it.
