### ISSUE TITLE
Is a range slider supposed to have moving label thumb labels like the other modes of operation?

### ISSUE THREAD

**Issue by broweratcognitecdotcom** [johnwalley/d3-simple-slider#36]
Just noticed that when I provide an array of numbers, e.g. [0, 100] to .default() that the moving thumb labels don't show up like in the other modes. Is this intended? Thanks. Nice work John.
RB

**Comment by johnwalley** [comment]
It is intended. In the sense that there's an explicit check in the code: https://github.com/johnwalley/d3-simple-slider/blob/master/src/slider.js#L285

However, I'm not sure it's the best behaviour. My original reason was to avoid handling the case where the labels overlap - making it difficult to read the values. Felt like the most pragmatic approach at the time. It might be worth revisiting if I look into the general problem of tick labels overlapping in some situations.

Thanks for bringing this to my attention 👍

**Comment by broweratcognitecdotcom** [comment]
Thanks for the quick response. You could display the slider values until the you stop sliding then fade them out and provide a tooltip on mouse over. Just an idea...

**Comment by johnwalley** [comment]
I think that's an excellent suggestion. I've created a new issue #39 to track it and will look to implement it next opportunity I get.
