### ISSUE TITLE
d3-simple-slider not working on IE 11

### ISSUE THREAD

**Issue by manaligaikwad** [johnwalley/d3-simple-slider#38]
Hi there,

I am using d3-simple-slider in one of my Vue.js project. It works perfectly fine on Chrome and Firefox but giving following error on IE 11:

![image](https://user-images.githubusercontent.com/12480500/55900776-2d484600-5b85-11e9-98bb-c6eda963801b.png)

Thanks!

**Comment by johnwalley** [comment]
Thanks for reporting this. I should get a chance to reproduce this next week.

From the screenshot it looks like a syntax error so possibly I'm using something which is unsupported by IE11 and is not being transpiled/poly-filled correctly.

**Comment by broweratcognitecdotcom** [comment]
Sorry for the duplicate. More info here: https://github.com/johnwalley/d3-simple-slider/issues/43

**Comment by johnwalley** [comment]
See #43
