### ISSUE TITLE
Does not support ie11 because of cross.js in d3-array

### ISSUE THREAD

**Issue by broweratcognitecdotcom** [johnwalley/d3-simple-slider#43]
See:
https://github.com/d3/d3-array/issues/87
https://github.com/d3/d3-array/issues/89

**Comment by johnwalley** [comment]
Thanks for this. I hadn't noticed that d3 modules had started to ship with non-ES5 features (other than using modules). I'll have to think about what the best solution is

**Comment by johnwalley** [comment]
I've reverted the dependency on d3-array back to version 1
