### ISSUE TITLE
Can't grab range slider knob

### ISSUE THREAD

**Issue by broweratcognitecdotcom** [johnwalley/d3-simple-slider#44]
If you are using a range slider with min 0 and max 100 and you drag the max to 0, then let it go, and try to drag the range max knob, you can only grab the range min knob. The range gets stuck at min 0 max 0. The range max knob should always have a higher 'z-order' so to say... If you click on the slider line it defaults to moving the range min knob.

**Comment by broweratcognitecdotcom** [comment]
The range max knob should ~always~ have a higher 'z-order' so to say...

**Comment by johnwalley** [comment]
Thanks for reporting this. I've made it a special case when both knobs are at the extreme ends of the slider. You now get the knob selected which allows you to get out of the situation described. This is released in v.1.5.3.
