### ISSUE TITLE
time slider first year on initial render the first year is always 1969

### ISSUE THREAD

**Issue by nharrisanalyst** [johnwalley/d3-simple-slider#6]
![image](https://user-images.githubusercontent.com/16217396/39656215-1a6ba114-4fb3-11e8-894d-33c6c4e63712.png)

**Comment by johnwalley** [comment]
Thanks for spotting this. I've pushed a fix which should now be live in v0.2.1

**Comment by nharrisanalyst** [comment]
thanks for making this!
