### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by weibao73** [johnwalley/d3-simple-slider#67]
How can I use d3-simple-slider in Typescript? i cannot find the type definitions in NPM.

**Comment by johnwalley** [comment]
I don't have any plans to create type definitions. If I receive more requests I'll revisit the decision.

I'm mostly concerned with the maintenance required to keep the definitions in sync with the library.

**Comment by quesog** [comment]
Consider this a second request for Typescript definitions. Thanks!

**Comment by johnwalley** [comment]
Let's re-open this issue. I'll attempt to create some type definitions and track progress at https://github.com/johnwalley/DefinitelyTyped. I'll give you both a ping when I have something ready to test.

**Comment by Ziuan** [comment]
Very nice @johnwalley , this would be a perfect addition!

**Comment by johnwalley** [comment]
First pass here: https://github.com/johnwalley/DefinitelyTyped/commit/712dcaa2b09b46633d77388abb31c9ef05ea2ef2

**Comment by johnwalley** [comment]
DefinitelyTyped PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43705

**Comment by johnwalley** [comment]
@weibao73 @quesog @Ziuan 

Merged and published! https://www.npmjs.com/package/@types/d3-simple-slider

Some methods do not yet have definitions but now we have something in place we can flesh out the definitions over time.
